site_name: 春雨的笔记本
repo_name: springrain-i
repo_url: https://github.com/springrain-i
theme:
  name: 'material'
  language: 'zh'
  icon:
    logo: material/notebook-outline #更改左上角的小图标
    repo: fontawesome/brands/github #git小图标
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font: false
  features: 
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes #指定节点index pages,与instant不兼容
    - navigation.top
    - search.share
    - search.highlight # 搜索出的文章中的关键字高亮
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
extra_css:
  - https://cdn.tonycrane.cc/jbmono/jetbrainsmono.css
  - https://cdn.tonycrane.cc/lxgw/lxgwscreen.css
  - css/custom.css
  - css/tasklist.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - toc:
      toc_depth: 2
  - admonition
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
nav:
  - Home:
    - index.md
  - Computer:
    - cs/index.md
    - C的函数: cs/c/Cstandard.md
    - python笔记: cs/Pynote.md
    - Shell笔记: cs/Shell.md
    - 计算机系统:
      - CSAPP: cs/system/CSAPP.md
    - 算法: cs/algorithm.md
  - Skill:
    - mkdocs使用记录: BasicSkill/mkdocs.md
    - WSL使用记录: BasicSkill/wsl.md
    - GitHub学生认证: BasicSkill/GitHub.md
    - 杂项: BasicSkill/else.md
    - Git命令行: BasicSkill/GitHelp.md
    - vscode中自定义快捷键 : BasicSkill/shortcuts.md
    - 修改windows设备名称: BasicSkill/Changename.md
    - verilog语法检查: BasicSkill/Verilog.md
  - Diary:
    - Diary/index.md
    - 日记: Diary/record.md
    - 我看的影剧: Diary/video.md
    - 2024年终总结: Diary/2024.md
    - 诗歌: Diary/Poetry.md


